load("@build_bazel_rules_apple//apple:ios.bzl", "ios_framework")

ios_framework(
    name = "TinyConstraints",
    bundle_id = "com.r.TinyConstraints",
    infoplists = [
        "TinyConstraints-Info.plist"
    ],
    minimum_os_version = "12.0",
    families = [
        "iphone"
    ],
    visibility = ["//visibility:public"]
)
