platform :ios, '12.0'

install! 'cocoapods', integrate_targets: false

target 'MovieBOOM' do
    pod 'MovieBOOMThrift',
        :git => "https://github.com/muizidn/movieboomgo.git",
        :branch => "main"
end